name: Michael Hansen Artist and Photograher
favicon: null
layout_spectrum: 0.77086
typography_spectrum: 0.51386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#323c48'
    - '#d7ced1'
    - '#829292'
    - '#b17958'
  brandStrength: 0.18172579794190824
  lightness: 0.0625
  saturation: 0.4743378725834191
  rhythmicContrast: 0.7935431923251599
purpose: []
