name: Michael Hansen Artist and Photograher
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64639
title: Michael Hansen - Artist and Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c2c1bc'
    - '#4c2a0f'
    - '#555b57'
    - '#878e86'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
